### ISSUE TITLE
Ufront-mvc client side?

### ISSUE THREAD

**Issue by cambiata** [ufront/ufront#10]
Hi Jason! Is it possible to run a (minimal) clientside ufront-mvc implementation today?
If so, could you give a clue how to start?

**Comment by fullofcaffeine** [comment]
@cambiata Curious about your experiences with ufront and Angular, how did it go? Did you use Haxe on the client-side with Angular as well? I'm currently using Angular with Coffeescript and Rails on the backend, but looking forward to trying ufront for the backend (Neko) soon.

**Comment by fullofcaffeine** [comment]
@jasononeil Great work on ufront so far, keep it up!

**Comment by jasononeil** [comment]
Some good news:
https://github.com/ufront/ufront-mvc/commit/7c0d9a331e2ee1c43466b498900132cfd6c65616

I've got ufront-mvc running client side, using the new `ufront.app.ClientJsApplication` rather than `ufront.app.UfrontApplication`.  You can re-use the same controllers and views.  The first visit loads on the server, the subsequent visits render on the client, making HTTP calls as necessary to fetch views or make API calls(*).

It works using Pushstate for detecting page changes, creates a HttpContext based on the browser, and executes it as per normal.  For now the result is printed to the browser by replacing the contents of `<head>` and `<body>`, obviously I will try come up with something better later :)

There's been many changes to quite a few libraries, so it might take me a day or two to clean them all up and release new versions.  I'll update the "hello world" to demonstrate once that's done too.

**Comment by jasononeil** [comment]
Some good news:
https://github.com/ufront/ufront-mvc/commit/7c0d9a331e2ee1c43466b498900132cfd6c65616

I've got ufront-mvc running client side, using the new `ufront.app.ClientJsApplication` rather than `ufront.app.UfrontApplication`.  You can re-use the same controllers and views.  The first visit loads on the server, the subsequent visits render on the client, making HTTP calls as necessary to fetch views or make API calls(*).

It works using Pushstate for detecting page changes, creates a HttpContext based on the browser, and executes it as per normal.  For now the result is printed to the browser by replacing the contents of `<head>` and `<body>`, obviously I will try come up with something better later :)

There's been many changes to quite a few libraries, so it might take me a day or two to clean them all up and release new versions.  I'll update the "hello world" to demonstrate once that's done too.

**Comment by cambiata** [comment]
Cool! :-)
