### ISSUE TITLE
ufront website fails on iPad/Safari

### ISSUE THREAD

**Issue by markknol** [ufront/ufront#21]
When I open the ufront.net website on Safari (iPad 2, iOS 8.3) it automatically redirects to the error page.

> **Whoops...**
> Internal server error
> details 

Tapping on _details_ does nothing.

**Comment by jasononeil** [comment]
Yes it's quite embarrassing.  I intended to fix it immediately after the conference but haven't had a chance until now.  I'll investigate it the error now.

(The details will not show up because the website is not compiled in debug mode, so the stack trace is not available.  I might just hide it if debug is not enabled.)
