### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by ncannasse** [ufront/ufront#22]
The API doc of ufront should filter out all packages that are not ufront specific (haxe, js, minject, etc.) this can be done with a macro exclude when generating documentation I think.

**Comment by jasononeil** [comment]
That is a good point.  Rather than exclude it from the documentation I have hidden it with CSS.  

This has the advantage of the documentation still being present if someone clicks on a link to a class in one of the dependencies (or in the standard library), rather than the link simply not doing anything.

I've also left the dependencies available in the search.  The two main dependencies (minject, tink_core) both have very good README documentation but do not have generated API documentation online, so I think it is useful to include it here.
